# -*- coding: utf-8 -*-
"""stage_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vEIPoQ_lum00CZcFK_ug3baRGPCrgpZ6
"""

#import kagglehub
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
import shutil
import cv2
import numpy as np
from pathlib import Path
from collections import Counter
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
import torch.optim as optim

# pathCF = kagglehub.dataset_download("tuyenldvn/caucafall")
# print("Path to dataset files:", pathCF)

# #-------------------------------------------------------------------------------
# # Copying datasets into content/ from session's cache/
# #-------------------------------------------------------------------------------

# # Source directories
# CFALL_SRC = "/root/.cache/kagglehub/datasets/tuyenldvn/caucafall/versions/2/Dataset CAUCAFall/CAUCAFall"
# # Target directories
# CFALL_DST = "/content/CAUCA_FALL"

# def move_dataset(src, dst):
#     if os.path.exists(dst):
#         print(f"{dst} already exists. Skipping copy.")
#     else:
#         shutil.copytree(src, dst)
#         print(f"Copied dataset to {dst}")

# # Move datasets
# move_dataset(CFALL_SRC, CFALL_DST)

import json
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d

# =====================================================
# CONFIG
# =====================================================
VIDEO_PATH = r"/content/CAUCA_FALL/Subject.3/Hop/HopS3.avi"   # works for .avi or .mp4
CKPT_PATH  = r"/content/best_model_fold3.pth"

CLIP_LEN   = 32
FRAME_SIZE = 224
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =====================================================
# MODEL
# =====================================================
class Stage1_3DCNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv3d(3,64,(3,7,7),(1,2,2),(1,3,3),padding_mode='replicate')
        self.bn1 = nn.BatchNorm3d(64)
        self.pool1 = nn.MaxPool3d((1,3,3),(1,2,2),(0,1,1))

        self.conv2 = nn.Conv3d(64,128,3, padding=1, padding_mode='replicate')
        self.bn2 = nn.BatchNorm3d(128)
        self.pool2 = nn.MaxPool3d(2,2)

        self.conv3 = nn.Conv3d(128,256,3,padding=1, padding_mode='replicate')
        self.bn3 = nn.BatchNorm3d(256)

        self.conv4 = nn.Conv3d(256,256,3,padding=1, padding_mode='replicate')
        self.bn4 = nn.BatchNorm3d(256)

        self.global_pool = nn.AdaptiveAvgPool3d((1,1,1))
        self.dropout = nn.Dropout(0.5)
        self.fc = nn.Linear(256,2)

    def forward(self,x, return_saliency=False):

        x = self.pool1(F.relu(self.bn1(self.conv1(x))))
        x = self.pool2(F.relu(self.bn2(self.conv2(x))))
        x = F.relu(self.bn3(self.conv3(x)))   # <-- saliency layer

       # --- SALIENCY (Improved with Edge Gating) ---
        sal = x.detach().pow(2).mean(dim=(1,3,4))  # (B, T')

        # Create a mask to dampen the very first and last temporal indices
        # T' is likely 16 here because of pool2
        T_prime = sal.shape[1]
        mask = torch.ones(T_prime).to(sal.device)
        mask[0] = 0.05  # Strongly suppress the first frame index
        mask[-1] = 0.5  # Slightly suppress the last
        sal = sal * mask

        # Now apply your scaling
        min_val = sal.min(dim=1, keepdim=True)[0]
        max_val = sal.max(dim=1, keepdim=True)[0]
        sal = (sal - min_val) / (max_val - min_val + 1e-6)

        # Softmax with temperature (5.0) helps highlight the fall peak
        sal = F.softmax(sal * 5.0, dim=1)

        #sal  = sal / (sal.sum(dim=1, keepdim=True) + 1e-6)

        x = F.relu(self.bn4(self.conv4(x)))
        x = self.global_pool(x).flatten(1)
        x = self.dropout(x)
        logits = self.fc(x)

        if return_saliency:
            return logits, sal
        return logits

# =====================================================
# LOAD MODEL
# =====================================================
model = Stage1_3DCNN().to(DEVICE)
model.load_state_dict(torch.load(CKPT_PATH, map_location=DEVICE))
model.eval()

# =====================================================
# UNIFORM SAMPLING
# =====================================================
cap = cv2.VideoCapture(VIDEO_PATH)
assert cap.isOpened(), "Cannot open video"

total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
assert total_frames > 0, "Empty video"

indices = np.linspace(0, total_frames-1, CLIP_LEN).astype(int)

frames = []
for idx in indices:
    cap.set(cv2.CAP_PROP_POS_FRAMES, int(idx))
    ret, frame = cap.read()
    if not ret:
        raise RuntimeError("Frame read failed")

    frame = cv2.resize(frame, (FRAME_SIZE, FRAME_SIZE))
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frames.append(frame)

cap.release()

frames_np = np.array(frames).astype(np.float32) / 255.0
clip = torch.from_numpy(frames_np).permute(3,0,1,2).unsqueeze(0).to(DEVICE)

# =====================================================
# RUN MODEL
# =====================================================
with torch.no_grad():
    logits, saliency = model(clip, return_saliency=True)

saliency = saliency.squeeze(0).cpu().numpy()

# Interpolate from 16 → 32 (since pool2 halves T)
saliency_interp = np.interp(
    np.linspace(0, len(saliency)-1, CLIP_LEN),
    np.arange(len(saliency)),
    saliency
)

# Smooth curve
saliency_smooth = gaussian_filter1d(saliency_interp, sigma=1.2)

print("Logits:", logits.cpu().numpy())
print("Raw Saliency:", saliency_interp)

# =====================================================
# PLOT CLEANLY
# =====================================================
fig = plt.figure(figsize=(18,12))

# ---- Saliency Curve (Top Full Width) ----
ax_curve = plt.subplot(5, 1, 1)
ax_curve.plot(saliency_interp, label="Raw")
ax_curve.plot(saliency_smooth, linewidth=2, label="Smoothed")
ax_curve.set_title("Temporal Saliency Curve")
ax_curve.set_xlabel("Frame Index")
ax_curve.set_ylabel("Saliency")
ax_curve.legend()
ax_curve.grid(True)

# ---- Frame Grid (4 rows x 8 cols) ----
rows = 4
cols = 8

for i in range(CLIP_LEN):
    ax = plt.subplot(5, cols, cols + i + 1)
    ax.imshow(frames[i])
    ax.set_title(f"{i}\nw={saliency_smooth[i]:.3f}", fontsize=8)
    ax.axis("off")

plt.tight_layout()
plt.savefig("saliency_visualization.png", dpi=300)
plt.show()

print("Saved as saliency_visualization.png")

def get_global_active_window(saliency_values, energy_threshold=0.15):
    # 1. Standardize and find 'Active' frames
    # We use a lower multiplier (0.5) to be more inclusive of "pre-fall" motion
    threshold = np.mean(saliency_values) + (0.5 * np.std(saliency_values))
    is_active = saliency_values > threshold

    # 2. Label all contiguous islands
    from scipy.ndimage import label
    labels, num_features = label(is_active)

    if num_features == 0:
        return 0, len(saliency_values) - 1, "Static/Uniform"

    total_energy = np.sum(saliency_values)
    significant_indices = []

    # 3. Filter islands by Energy Contribution (Global Context)
    for i in range(1, num_features + 1):
        mask = (labels == i)
        region_energy = np.sum(saliency_values[mask])

        # If this peak is a significant part of the whole clip's motion
        if (region_energy / total_energy) > energy_threshold:
            significant_indices.extend(np.where(mask)[0])

    if not significant_indices:
        # Fallback to the single highest peak if nothing meets the energy threshold
        peak_idx = np.argmax(saliency_values)
        return max(0, peak_idx-2), min(len(saliency_values)-1, peak_idx+2), "Peak Only"

    # 4. The Global Varying K
    start = min(significant_indices)
    end = max(significant_indices)

    return start, end, "Global Event Zone"

# Example usage in your pipeline:
start, end, status = get_global_active_window(saliency_smooth)
varying_k = end - start + 1

print(f"Status: {status} | Window: {start} to {end} | Varying K: {varying_k}")

# =====================================================
# SAVE STAGE 1 OUTPUT FOR STAGE 2
# =====================================================

# Prepare the data dictionary
# We include original video path, the localized window,
# the importance weights, and the actual frame numbers sampled.
stage1_data = {
    "video_path": VIDEO_PATH,
    "active_window": [int(start), int(end)],
    "varying_k": int(varying_k),
    "detection_status": status,
    "saliency_weights": saliency_smooth.tolist(),
    "clip_indices": indices.tolist()  # Maps 0-31 indices to actual video frame numbers
}

# Define the output path
json_output_path = "/content/stage1_output.json"

# Write to JSON
with open(json_output_path, "w") as f:
    json.dump(stage1_data, f, indent=4)

print("\n" + "="*50)
print(f"STAGE 1 JSON GENERATED: {json_output_path}")
print(f"Status: {status}")
print(f"Target Window: Frames {start} to {end} (K={varying_k})")
print("="*50)



# ====== STAGE-2: Pose estimation, skeleton visualization, stage2_output.json ======
import os, sys, json, math, time
import numpy as np
import cv2

# ---------- CONFIG ----------
STAGE1_JSON = "stage1_output.json"
STAGE2_JSON = "stage2_output.json"
VIS_DIR = "/content/stage2_vis"
os.makedirs(VIS_DIR, exist_ok=True)

YOLO_MODEL = "yolov8m-pose.pt"   # Medium model is robust for movement
IMGSZ = 640                     # Optimal size for YOLOv8 accuracy/speed
CONF = 0.1                      # Low threshold to catch blurred/difficult falls
IOU  = 0.5
NUM_KP = 17                     # COCO standard joints

# COCO Skeleton pairs for drawing connecting lines
SKELETON_LINES = [
    (5, 6), (5, 11), (6, 12), (11, 12),       # Torso
    (5, 7), (7, 9), (6, 8), (8, 10),           # Arms
    (11, 13), (13, 15), (12, 14), (14, 16),   # Legs
    (0, 1), (0, 2), (1, 3), (2, 4)             # Face
]

# ---------- load stage1 json ----------
if not os.path.exists(STAGE1_JSON):
    raise FileNotFoundError(f"{STAGE1_JSON} not found. Run Stage-1 first.")

with open(STAGE1_JSON, "r") as f:
    s1 = json.load(f)

VIDEO_PATH = s1["video_path"]
clip_indices = s1["clip_indices"]
active_window = s1["active_window"]
clip_start, clip_end = int(active_window[0]), int(active_window[1])
frame_numbers = [int(clip_indices[i]) for i in range(clip_start, clip_end+1)]

# ---------- ensure ultralytics installed ----------
try:
    from ultralytics import YOLO
except Exception:
    !{sys.executable} -m pip install -q ultralytics
    from ultralytics import YOLO

print("Loading YOLO model...")
model = YOLO(YOLO_MODEL)

# ---------- run inference and save overlays ----------
cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise RuntimeError("Cannot open video: " + VIDEO_PATH)

frame_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

detections_px = {}
bboxes_px = {}
scores = {}

print(f"Processing {len(frame_numbers)} frames from Stage-1 window...")

for fnum in frame_numbers:
    cap.set(cv2.CAP_PROP_POS_FRAMES, int(fnum))
    ret, frame = cap.read()
    if not ret:
        detections_px[fnum], bboxes_px[fnum], scores[fnum] = None, None, 0.0
        continue

    # Inference
    results = model.predict(source=frame, imgsz=IMGSZ, conf=CONF, iou=IOU, verbose=False)
    vis = frame.copy()

    if len(results) > 0 and len(results[0].boxes) > 0:
        # Get best detection (highest confidence)
        best_idx = results[0].boxes.conf.argmax()
        kp_data = results[0].keypoints.data[best_idx].cpu().numpy() # (17, 3)
        bbox = results[0].boxes.xyxy[best_idx].cpu().numpy()      # [x1, y1, x2, y2]

        detections_px[fnum] = kp_data[:, :2]
        scores[fnum] = float(results[0].boxes.conf[best_idx])

        # Convert bbox to [cx, cy, w, h] for JSON consistency
        bboxes_px[fnum] = [
            float((bbox[0]+bbox[2])/2), float((bbox[1]+bbox[3])/2),
            float(bbox[2]-bbox[0]), float(bbox[3]-bbox[1])
        ]

        # --- DRAW SKELETON ---
        # 1. Draw Lines (Cyan)
        for start_j, end_j in SKELETON_LINES:
            pt1, pt2 = kp_data[start_j], kp_data[end_j]
            if pt1[2] > 0.3 and pt2[2] > 0.3: # Confidence gate for clean visual
                cv2.line(vis, (int(pt1[0]), int(pt1[1])), (int(pt2[0]), int(pt2[1])), (255, 255, 0), 2)

        # 2. Draw Keypoint Dots (Green/Pink)
        for i, (x, y, conf) in enumerate(kp_data):
            if conf > 0.3:
                color = (0, 255, 0) if i > 4 else (255, 0, 255) # Pink for face, green for body
                cv2.circle(vis, (int(x), int(y)), 4, color, -1)

        # 3. Draw Bounding Box (Red)
        cv2.rectangle(vis, (int(bbox[0]), int(bbox[1])), (int(bbox[2]), int(bbox[3])), (0, 0, 255), 2)
        cv2.putText(vis, f"Person {scores[fnum]:.2f}", (int(bbox[0]), int(bbox[1])-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1)
    else:
        detections_px[fnum], bboxes_px[fnum], scores[fnum] = None, None, 0.0

    save_path = os.path.join(VIS_DIR, f"frame_{fnum:05d}.png")
    cv2.imwrite(save_path, vis)

cap.release()

# ---------- normalize and interpolate ----------
def norm_kp(kp, W, H):
    if kp is None: return [[None, None]] * NUM_KP
    return [[float(x/W), float(y/H)] for x, y in kp]

detections_norm = {f: norm_kp(detections_px[f], frame_w, frame_h) for f in frame_numbers}
bboxes_norm = {}
for f in frame_numbers:
    bx = bboxes_px[f]
    bboxes_norm[f] = [bx[0]/frame_w, bx[1]/frame_h, bx[2]/frame_w, bx[3]/frame_h] if bx else [None]*4

# Linear interpolation to fill gaps where YOLO missed a person
def interpolate(frames, dets, num_kp=17):
    L = len(frames)
    xs, ys = np.full((L, num_kp), np.nan), np.full((L, num_kp), np.nan)
    for i, f in enumerate(frames):
        for j, pt in enumerate(dets[f]):
            if pt[0] is not None: xs[i,j], ys[i,j] = pt[0], pt[1]

    idx = np.arange(L)
    for j in range(num_kp):
        mask = ~np.isnan(xs[:,j])
        if mask.any():
            xs[:,j] = np.interp(idx, idx[mask], xs[mask,j])
            ys[:,j] = np.interp(idx, idx[mask], ys[mask,j])

    return {f: [[float(xs[i,j]), float(ys[i,j])] for j in range(num_kp)] for i, f in enumerate(frames)}

interp_results = interpolate(frame_numbers, detections_norm)

# ---------- compute physics features ----------
frame_data = []
prev_hip = None

for f in frame_numbers:
    kp = interp_results[f]
    # Indices: 5,6 Shld | 11,12 Hip
    m_sh = [(kp[5][0]+kp[6][0])/2, (kp[5][1]+kp[6][1])/2]
    m_hp = [(kp[11][0]+kp[12][0])/2, (kp[11][1]+kp[12][1])/2]

    # Feature 1: Tilt Angle
    tilt = abs(math.degrees(math.atan2(m_sh[0]-m_hp[0], -(m_sh[1]-m_hp[1]))))
    # Feature 2: Vertical Velocity (Y-diff)
    vel = float(m_hp[1] - prev_hip[1]) if prev_hip else 0.0
    prev_hip = m_hp
    # Feature 3: Aspect Ratio
    bx = bboxes_norm[f]
    hw = float(bx[3]/bx[2]) if bx[2] and bx[2] > 0 else 0.0
    # Feature 4: Ground Proximity (1.0 - Y_shoulder)
    gp = float(1.0 - m_sh[1])

    frame_data.append({
        "frame_idx": f,
        "keypoints": kp,
        "normalized_bbox": bx,
        "score": scores[f],
        "features": {"tilt_angle": tilt, "vertical_velocity": vel, "h_w_ratio": hw, "ground_proximity": gp}
    })

with open(STAGE2_JSON, "w") as f:
    json.dump({"frame_data": frame_data}, f, indent=2)

print(f"Stage-2 Complete. JSON saved. {len(frame_numbers)} skeletons drawn in {VIS_DIR}")

# -------- CELL 3: Visualization — combine stage1_output.json + stage2 overlays into combined images --------
# Edit STAGE2_VIS_DIR if your Stage-2 overlays were saved elsewhere.

import os, json, cv2, numpy as np

STAGE1_JSON = "stage1_output.json"
STAGE2_JSON = "stage2_output.json"
STAGE2_VIS_DIR = "/content/stage2_vis"   # change to local folder if you ran Stage-2 locally
OUT_DIR = "stage_results"
os.makedirs(OUT_DIR, exist_ok=True)

if not os.path.exists(STAGE1_JSON):
    raise FileNotFoundError(f"{STAGE1_JSON} not found. Run Stage-1 quick inference (Cell 2 with GENERATE_SAMPLE_INFERENCE=True) or produce stage1_output.json.")

if not os.path.exists(STAGE2_JSON):
    print(f"Warning: {STAGE2_JSON} not found. You can still create combined images if stage2 overlays exist in {STAGE2_VIS_DIR} and you have stage1_output.json.")

with open(STAGE1_JSON, "r") as f:
    s1 = json.load(f)

clip_indices = s1.get("clip_indices")
active_window = s1.get("active_window")
saliency = np.array(s1.get("saliency_weights", [])) if s1.get("saliency_weights") else None

if clip_indices is None or active_window is None:
    raise ValueError("stage1_output.json missing keys clip_indices or active_window.")

clip_start, clip_end = int(active_window[0]), int(active_window[1])
clip_positions = list(range(clip_start, clip_end+1))
frame_numbers = [int(clip_indices[p]) for p in clip_positions]

# load stage2 mapping if available
frame_data_map = {}
if os.path.exists(STAGE2_JSON):
    with open(STAGE2_JSON, "r") as f:
        s2 = json.load(f)
    for entry in s2.get("frame_data", []):
        frame_data_map[int(entry["frame_idx"])] = entry

for cp, frame_num in zip(clip_positions, frame_numbers):
    overlay_path = os.path.join(STAGE2_VIS_DIR, f"frame_{frame_num:05d}.png")
    if not os.path.exists(overlay_path):
        print("Overlay missing for frame", frame_num, "at", overlay_path, "- skipping.")
        continue
    img = cv2.imread(overlay_path)[:,:,::-1]
    h,w,_ = img.shape

    # build small saliency strip (optional)
    if saliency is not None:
        norm = (saliency - saliency.min()) / (saliency.max()-saliency.min()+1e-8)
        strip = 255 * np.ones((80, w, 3), dtype=np.uint8)
        pts = [ (int(j*(w/len(norm))), 40 - int(norm[j]*30)) for j in range(len(norm)) ]
        for j in range(len(pts)-1):
            cv2.line(strip, pts[j], pts[j+1], (255,0,0), 2)
    else:
        strip = 255 * np.ones((80, w, 3), dtype=np.uint8)

    combined = np.vstack([img, strip])
    # annotate with stage2 features if present
    info = frame_data_map.get(frame_num)
    if info:
        feats = info.get("features", {})
        txt = f"Frame {frame_num} | tilt={feats.get('tilt_angle')} v_vel={feats.get('vertical_velocity')} h/w={feats.get('h_w_ratio')} gp={feats.get('ground_proximity')}"
    else:
        txt = f"Frame {frame_num} | no stage2 entry"
    cv2.putText(combined, txt, (10,20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1)

    out_path = os.path.join(OUT_DIR, f"combined_{frame_num:05d}.png")
    cv2.imwrite(out_path, combined[:,:,::-1])
    print("Saved combined:", out_path)

print("Visualization complete. Check folder:", OUT_DIR)